version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: npm
  directory: "/packages/tokens"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: npm
  directory: "/packages/styles"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: npm
  directory: "/packages/components"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    prefix: chore
    include: scope
