version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    # dependabot does not work with yarn v2, disabling for now
    open-pull-requests-limit: 0
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: npm
    directory: "/packages/tokens"
    schedule:
      interval: daily
    # dependabot does not work with yarn v2, disabling for now
    open-pull-requests-limit: 0
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: npm
    directory: "/packages/components"
    schedule:
      interval: daily
    # dependabot does not work with yarn v2, disabling for now
    open-pull-requests-limit: 0
    commit-message:
      prefix: chore
      include: scope
