version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    # Disable dependabot in favor of renovate
    open-pull-requests-limit: 0
    # Note: security updates will always apply (targeting `main`)
    # https://docs.github.com/en/code-security/reference/supply-chain-security/dependabot-options-reference#target-branch-
    target-branch: "next"
    commit-message:
      prefix: chore
      include: scope
