ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.stories.ts"
  - "**/*.stories.tsx"
coverage:
  status:
    project:
      default:
        informational: true
    patch: off
# Post comment if there are changes in bundle size exceeding 1Kb
comment:
     require_bundle_changes: True
     bundle_change_threshold: "1Kb"