version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    commit_message:
      prefix: "chore"
      include_scope: true
  - package_manager: "javascript"
    directory: "/packages/components"
    update_schedule: "daily"
    commit_message:
      prefix: "chore"
      include_scope: true
  - package_manager: "javascript"
    directory: "/packages/styles"
    update_schedule: "daily"
    commit_message:
      prefix: "chore"
      include_scope: true
  - package_manager: "javascript"
    directory: "/packages/tokens"
    update_schedule: "daily"
    commit_message:
      prefix: "chore"
      include_scope: true