/* eslint-env node */
const {execSync} = require('child_process');
const fs = require('fs');

const ICON_FOLDER = 'src/icons';
const OUTPUT_FILE = 'src/util/allIcons.ts';

const iconFiles = fs
  .readdirSync(ICON_FOLDER, {withFileTypes: true})
  .filter((dirent) => dirent.isFile());

// convert 'close.svg' => 'close'
const iconNames = iconFiles.map((dirent) => {
  const svgMatches = dirent.name.match(/([\w\s-]*)\.svg$/);
  if (svgMatches) {
    const name = svgMatches[1];
    return `'${name}'`;
  }
});

const fileHeader = `
/**
 * Exports an array of all icon names.
 *
 * This file is generated, and you shouldn't manually modify it. It can be re-generated by
 * running \`yarn generate-icon-types\`.
 *
 * @generated
 */

`;

const output = `export const ALL_ICONS = [${iconNames}] as const;\n`;

fs.writeFileSync(OUTPUT_FILE, fileHeader + output);

execSync(`npx prettier --write ${OUTPUT_FILE}`);
