export const EdsColorBrand100 = '#F7F1FF'; // old token alias, remove with next major release
export const EdsColorBrand200 = '#C3C0FE'; // old token alias, remove with next major release
export const EdsColorBrand300 = '#A7A2FE'; // old token alias, remove with next major release
export const EdsColorBrand400 = '#928CFF'; // old token alias, remove with next major release
export const EdsColorBrand500 = '#766FFD'; // old token alias, remove with next major release
export const EdsColorBrand600 = '#574EFF'; // old token alias, remove with next major release
export const EdsColorBrand700 = '#433BDE'; // old token alias, remove with next major release
export const EdsColorBrand800 = '#312B9E'; // old token alias, remove with next major release
export const EdsColorBrandGrape100 = '#F7F1FF';
export const EdsColorBrandGrape200 = '#C3C0FE';
export const EdsColorBrandGrape300 = '#A7A2FE';
export const EdsColorBrandGrape400 = '#928CFF';
export const EdsColorBrandGrape500 = '#766FFD';
export const EdsColorBrandGrape600 = '#574EFF';
export const EdsColorBrandGrape700 = '#433BDE';
export const EdsColorBrandGrape800 = '#312B9E';
export const EdsColorNeutral100 = '#F3F3F3';
export const EdsColorNeutral200 = '#E8E8E9';
export const EdsColorNeutral300 = '#CAD1D8';
export const EdsColorNeutral400 = '#838C95';
export const EdsColorNeutral500 = '#58636F';
export const EdsColorNeutral600 = '#3C444C';
export const EdsColorNeutral700 = '#21272D';
export const EdsColorNeutral800 = '#21272D';
export const EdsColorNeutralWhite = '#FFFFFF';
export const EdsColorNeutralBlack = '#21272D';
export const EdsColorOtherMint100 = '#ECFFF5';
export const EdsColorOtherMint200 = '#B7E9CE';
export const EdsColorOtherMint300 = '#8FDCB3';
export const EdsColorOtherMint400 = '#59C88C';
export const EdsColorOtherMint500 = '#00A66A';
export const EdsColorOtherMint600 = '#008756';
export const EdsColorOtherMint700 = '#007349';
export const EdsColorOtherMint800 = '#005939';
export const EdsColorOtherYellow100 = '#FDF1D0';
export const EdsColorOtherYellow200 = '#FFEBB3';
export const EdsColorOtherYellow300 = '#FFDD80';
export const EdsColorOtherYellow400 = '#F7BE2D';
export const EdsColorOtherYellow500 = '#F79D2D';
export const EdsColorOtherYellow600 = '#BF7300';
export const EdsColorOtherYellow700 = '#9E5B03';
export const EdsColorOtherYellow800 = '#854C03';
export const EdsColorOtherLemon = '#FCFF00';
export const EdsColorOtherOrange100 = '#FFF1E9';
export const EdsColorOtherOrange200 = '#FFCBA6';
export const EdsColorOtherOrange300 = '#FFB077';
export const EdsColorOtherOrange400 = '#F6924A';
export const EdsColorOtherOrange500 = '#E06C00';
export const EdsColorOtherOrange600 = '#C64600';
export const EdsColorOtherOrange700 = '#AC3400';
export const EdsColorOtherOrange800 = '#852800';
export const EdsColorOtherRuby100 = '#FFEBF0';
export const EdsColorOtherRuby200 = '#FFCCD8';
export const EdsColorOtherRuby300 = '#FB90B0';
export const EdsColorOtherRuby400 = '#F76C96';
export const EdsColorOtherRuby500 = '#F1497C';
export const EdsColorOtherRuby600 = '#D41E52';
export const EdsColorOtherRuby700 = '#BD0044';
export const EdsColorOtherRuby800 = '#8F0134';
export const EdsColorWhite = '#FFFFFF'; // old token alias, remove with next major release
export const EdsColorBlack = '#21272D'; // old token alias, remove with next major release
export const EdsColorAlert100 = '#FFEBF0'; // old token alias, remove with next major release
export const EdsColorAlert200 = '#FFCCD8'; // old token alias, remove with next major release
export const EdsColorAlert300 = '#FB90B0'; // old token alias, remove with next major release
export const EdsColorAlert400 = '#F76C96'; // old token alias, remove with next major release
export const EdsColorAlert500 = '#F1497C'; // old token alias, remove with next major release
export const EdsColorAlert600 = '#D41E52'; // old token alias, remove with next major release
export const EdsColorAlert700 = '#BD0044'; // old token alias, remove with next major release
export const EdsColorAlert800 = '#8F0134'; // old token alias, remove with next major release
export const EdsColorSuccess100 = '#ECFFF5'; // old token alias, remove with next major release
export const EdsColorSuccess200 = '#B7E9CE'; // old token alias, remove with next major release
export const EdsColorSuccess300 = '#8FDCB3'; // old token alias, remove with next major release
export const EdsColorSuccess400 = '#59C88C'; // old token alias, remove with next major release
export const EdsColorSuccess500 = '#00A66A'; // old token alias, remove with next major release
export const EdsColorSuccess600 = '#008756'; // old token alias, remove with next major release
export const EdsColorSuccess700 = '#007349'; // old token alias, remove with next major release
export const EdsColorSuccess800 = '#005939'; // old token alias, remove with next major release
export const EdsColorInfo100 = '#F1F9FF';
export const EdsColorInfo200 = '#B0D5FF';
export const EdsColorInfo300 = '#7FB9FD';
export const EdsColorInfo400 = '#5CA7FF';
export const EdsColorInfo500 = '#328EFB';
export const EdsColorInfo600 = '#1977CD';
export const EdsColorInfo700 = '#0563B8';
export const EdsColorWarning100 = '#FFF1E9'; // old token alias, remove with next major release
export const EdsColorWarning200 = '#FFCBA6'; // old token alias, remove with next major release
export const EdsColorWarning300 = '#FFB077'; // old token alias, remove with next major release
export const EdsColorWarning400 = '#F6924A'; // old token alias, remove with next major release
export const EdsColorWarning500 = '#E06C00'; // old token alias, remove with next major release
export const EdsColorWarning600 = '#C64600'; // old token alias, remove with next major release
export const EdsColorWarning700 = '#AC3400'; // old token alias, remove with next major release
export const EdsColorWarning800 = '#852800'; // old token alias, remove with next major release
export const EdsColorYellow100 = '#FDF1D0'; // old token alias, remove with next major release
export const EdsColorYellow500 = '#F79D2D'; // old token alias, remove with next major release
export const EdsColorHighlight100 = '#FF9FEC';
export const EdsColorHighlight200 = '#FFBEAA';
export const EdsColorHighlight300 = '#FCFF00'; // old token alias, remove with next major release
export const EdsColorHighlight400 = '#9DFFA4';
export const EdsColorHighlight500 = '#00F1FF';
export const EdsColorHighlight600 = '#CFC9FF';
export const EdsThemeColorBackgroundNeutralDefault = '#FFFFFF';
export const EdsThemeColorBackgroundNeutralDefaultHover = '#F3F3F3';
export const EdsThemeColorBackgroundNeutralSubtle = '#F3F3F3';
export const EdsThemeColorBackgroundNeutralSubtleHover = '#E8E8E9';
export const EdsThemeColorBackgroundNeutralMedium = '#E8E8E9';
export const EdsThemeColorBackgroundNeutralMediumHover = '#CAD1D8';
export const EdsThemeColorBackgroundBrandPrimaryDefault = '#F7F1FF';
export const EdsThemeColorBackgroundBrandPrimaryStrong = '#574EFF';
export const EdsThemeColorBackgroundBrandPrimaryStrongHover = '#312B9E';
export const EdsThemeColorBackgroundUtilitySuccess = '#ECFFF5';
export const EdsThemeColorBackgroundUtilityWarning = '#FFF1E9';
export const EdsThemeColorBackgroundUtilityError = '#FFEBF0';
export const EdsThemeColorBackgroundGradeCompleteDefault = '#008756';
export const EdsThemeColorBackgroundGradeCompleteSubtle = '#ECFFF5';
export const EdsThemeColorBackgroundGradeReviseDefault = '#F7BE2D';
export const EdsThemeColorBackgroundGradeReviseSubtle = '#FDF1D0';
export const EdsThemeColorBackgroundGradeStopDefault = '#D41E52';
export const EdsThemeColorBackgroundGradeStopSubtle = '#FFEBF0';
export const EdsThemeColorBackgroundDisabled = '#CAD1D8';
export const EdsThemeColorBorderNeutralSubtle = '#E8E8E9';
export const EdsThemeColorBorderNeutralSubtleHover = '#CAD1D8';
export const EdsThemeColorBorderNeutralDefault = '#CAD1D8';
export const EdsThemeColorBorderNeutralDefaultHover = '#838C95';
export const EdsThemeColorBorderNeutralStrong = '#838C95';
export const EdsThemeColorBorderNeutralStrongHover = '#58636F';
export const EdsThemeColorBorderBrandPrimarySubtle = '#C3C0FE';
export const EdsThemeColorBorderBrandPrimary = '#A7A2FE';
export const EdsThemeColorBorderBrandPrimaryStrong = '#928CFF';
export const EdsThemeColorBorderUtilitySuccessSubtle = '#B7E9CE';
export const EdsThemeColorBorderUtilitySuccessDefault = '#8FDCB3';
export const EdsThemeColorBorderUtilitySuccessStrong = '#59C88C';
export const EdsThemeColorBorderUtilityWarningSubtle = '#FFCBA6';
export const EdsThemeColorBorderUtilityWarningDefault = '#FFB077';
export const EdsThemeColorBorderUtilityWarningStrong = '#F6924A';
export const EdsThemeColorBorderUtilityErrorSubtle = '#FFCCD8';
export const EdsThemeColorBorderUtilityErrorDefault = '#FB90B0';
export const EdsThemeColorBorderUtilityErrorStrong = '#F76C96';
export const EdsThemeColorBorderGradeComplete = '#8FDCB3';
export const EdsThemeColorBorderGradeReviseSubtle = '#FFEBB3';
export const EdsThemeColorBorderGradeReviseDefault = '#FFDD80';
export const EdsThemeColorBorderGradeReviseStrong = '#F7BE2D';
export const EdsThemeColorBorderGradeStop = '#FB90B0';
export const EdsThemeColorBorderDisabled = '#F3F3F3';
export const EdsThemeColorIconNeutralDefault = '#3C444C';
export const EdsThemeColorIconNeutralDefaultInverse = '#FFFFFF';
export const EdsThemeColorIconNeutralDefaultHover = '#21272D';
export const EdsThemeColorIconNeutralStrong = '#21272D';
export const EdsThemeColorIconNeutralStrongHover = '#21272D';
export const EdsThemeColorIconNeutralSubtle = '#58636F';
export const EdsThemeColorIconNeutralSubtleHover = '#3C444C';
export const EdsThemeColorIconLinkDefault = '#766FFD';
export const EdsThemeColorIconLinkDefaultHover = '#574EFF';
export const EdsThemeColorIconBrandPrimary = '#766FFD';
export const EdsThemeColorIconBrandPrimaryHover = '#574EFF';
export const EdsThemeColorIconUtilitySuccess = '#00A66A';
export const EdsThemeColorIconUtilitySuccessHover = '#008756';
export const EdsThemeColorIconUtilityWarning = '#E06C00';
export const EdsThemeColorIconUtilityWarningHover = '#C64600';
export const EdsThemeColorIconUtilityError = '#F1497C';
export const EdsThemeColorIconUtilityErrorHover = '#D41E52';
export const EdsThemeColorIconGradeComplete = '#00A66A';
export const EdsThemeColorIconGradeCompleteHover = '#00A66A';
export const EdsThemeColorIconGradeRevise = '#21272D';
export const EdsThemeColorIconGradeReviseHover = '#21272D';
export const EdsThemeColorIconGradeStop = '#F1497C';
export const EdsThemeColorIconGradeStopHover = '#F1497C';
export const EdsThemeColorIconDisabled = '#CAD1D8';
export const EdsThemeColorTextNeutralDefault = '#21272D';
export const EdsThemeColorTextNeutralDefaultInverse = '#FFFFFF';
export const EdsThemeColorTextNeutralStrong = '#21272D';
export const EdsThemeColorTextNeutralSubtle = '#3C444C';
export const EdsThemeColorTextLinkDefault = '#21272D';
export const EdsThemeColorTextLinkDefaultHover = '#21272D';
export const EdsThemeColorTextLinkStrong = '#433BDE';
export const EdsThemeColorTextLinkStrongHover = '#312B9E';
export const EdsThemeColorTextUtilitySuccess = '#007349';
export const EdsThemeColorTextUtilityWarning = '#AC3400';
export const EdsThemeColorTextUtilityError = '#BD0044';
export const EdsThemeColorTextGradeComplete = '#007349';
export const EdsThemeColorTextGradeRevise = '#21272D';
export const EdsThemeColorTextGradeStop = '#BD0044';
export const EdsThemeColorTextDisabled = '#CAD1D8';
export const EdsThemeColorTextBrandPrimary = '#433BDE';
export const EdsThemeColorTransparentBlack0 = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorTransparentBlack30 = 'rgba(0, 0, 0, .3)';
export const EdsThemeColorTransparentWhite0 = 'rgba(255, 255, 255, 0)';
export const EdsThemeColorBodyBackground = '#F3F3F3';
export const EdsThemeColorBodyBackgroundInverted = '#21272D';
export const EdsThemeColorButtonPrimaryBrandBackground = '#574EFF';
export const EdsThemeColorButtonPrimaryBrandBackgroundHover = '#433BDE';
export const EdsThemeColorButtonPrimaryBrandBackgroundActive = '#312B9E';
export const EdsThemeColorButtonPrimaryBrandBorder = '#574EFF';
export const EdsThemeColorButtonPrimaryBrandBorderHover = '#433BDE';
export const EdsThemeColorButtonPrimaryBrandBorderActive = '#312B9E';
export const EdsThemeColorButtonPrimaryBrandText = '#FFFFFF';
export const EdsThemeColorButtonPrimaryBrandTextHover = '#FFFFFF';
export const EdsThemeColorButtonPrimaryBrandTextActive = '#FFFFFF';
export const EdsThemeColorButtonPrimaryErrorBackground = '#D41E52';
export const EdsThemeColorButtonPrimaryErrorBackgroundHover = '#BD0044';
export const EdsThemeColorButtonPrimaryErrorBackgroundActive = '#8F0134';
export const EdsThemeColorButtonPrimaryErrorBorder = '#D41E52';
export const EdsThemeColorButtonPrimaryErrorBorderHover = '#BD0044';
export const EdsThemeColorButtonPrimaryErrorBorderActive = '#8F0134';
export const EdsThemeColorButtonPrimaryErrorText = '#FFFFFF';
export const EdsThemeColorButtonPrimaryErrorTextHover = '#FFFFFF';
export const EdsThemeColorButtonPrimaryErrorTextActive = '#FFFFFF';
export const EdsThemeColorButtonSecondaryBrandBackground = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonSecondaryBrandBackgroundHover = '#433BDE';
export const EdsThemeColorButtonSecondaryBrandBackgroundActive = '#312B9E';
export const EdsThemeColorButtonSecondaryBrandBorder = '#433BDE';
export const EdsThemeColorButtonSecondaryBrandBorderHover = '#433BDE';
export const EdsThemeColorButtonSecondaryBrandBorderActive = '#312B9E';
export const EdsThemeColorButtonSecondaryBrandText = '#433BDE';
export const EdsThemeColorButtonSecondaryBrandTextHover = '#FFFFFF';
export const EdsThemeColorButtonSecondaryBrandTextActive = '#FFFFFF';
export const EdsThemeColorButtonSecondaryNeutralBackground = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonSecondaryNeutralBackgroundHover = '#3C444C';
export const EdsThemeColorButtonSecondaryNeutralBackgroundActive = '#21272D';
export const EdsThemeColorButtonSecondaryNeutralBorder = '#3C444C';
export const EdsThemeColorButtonSecondaryNeutralBorderHover = '#3C444C';
export const EdsThemeColorButtonSecondaryNeutralBorderActive = '#21272D';
export const EdsThemeColorButtonSecondaryNeutralText = '#3C444C';
export const EdsThemeColorButtonSecondaryNeutralTextHover = '#FFFFFF';
export const EdsThemeColorButtonSecondaryNeutralTextActive = '#FFFFFF';
export const EdsThemeColorButtonSecondarySuccessBackground = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonSecondarySuccessBackgroundHover = '#007349';
export const EdsThemeColorButtonSecondarySuccessBackgroundActive = '#005939';
export const EdsThemeColorButtonSecondarySuccessBorder = '#007349';
export const EdsThemeColorButtonSecondarySuccessBorderHover = '#007349';
export const EdsThemeColorButtonSecondarySuccessBorderActive = '#005939';
export const EdsThemeColorButtonSecondarySuccessText = '#007349';
export const EdsThemeColorButtonSecondarySuccessTextHover = '#FFFFFF';
export const EdsThemeColorButtonSecondarySuccessTextActive = '#FFFFFF';
export const EdsThemeColorButtonSecondaryWarningBackground = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonSecondaryWarningBackgroundHover = '#AC3400';
export const EdsThemeColorButtonSecondaryWarningBackgroundActive = '#852800';
export const EdsThemeColorButtonSecondaryWarningBorder = '#AC3400';
export const EdsThemeColorButtonSecondaryWarningBorderHover = '#AC3400';
export const EdsThemeColorButtonSecondaryWarningBorderActive = '#852800';
export const EdsThemeColorButtonSecondaryWarningText = '#AC3400';
export const EdsThemeColorButtonSecondaryWarningTextHover = '#FFFFFF';
export const EdsThemeColorButtonSecondaryWarningTextActive = '#FFFFFF';
export const EdsThemeColorButtonSecondaryErrorBackground = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonSecondaryErrorBackgroundHover = '#BD0044';
export const EdsThemeColorButtonSecondaryErrorBackgroundActive = '#8F0134';
export const EdsThemeColorButtonSecondaryErrorBorder = '#BD0044';
export const EdsThemeColorButtonSecondaryErrorBorderHover = '#BD0044';
export const EdsThemeColorButtonSecondaryErrorBorderActive = '#8F0134';
export const EdsThemeColorButtonSecondaryErrorText = '#BD0044';
export const EdsThemeColorButtonSecondaryErrorTextHover = '#FFFFFF';
export const EdsThemeColorButtonSecondaryErrorTextActive = '#FFFFFF';
export const EdsThemeColorButtonIconBrandBackground = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonIconBrandBackgroundHover = '#F7F1FF';
export const EdsThemeColorButtonIconBrandBackgroundActive = '#433BDE';
export const EdsThemeColorButtonIconBrandBorder = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonIconBrandBorderHover = '#F7F1FF';
export const EdsThemeColorButtonIconBrandBorderActive = '#433BDE';
export const EdsThemeColorButtonIconBrandText = '#433BDE';
export const EdsThemeColorButtonIconBrandTextHover = '#433BDE';
export const EdsThemeColorButtonIconBrandTextActive = '#FFFFFF';
export const EdsThemeColorButtonIconNeutralBackground = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonIconNeutralBackgroundHover = '#F3F3F3';
export const EdsThemeColorButtonIconNeutralBackgroundActive = '#3C444C';
export const EdsThemeColorButtonIconNeutralBorder = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonIconNeutralBorderHover = '#F3F3F3';
export const EdsThemeColorButtonIconNeutralBorderActive = '#3C444C';
export const EdsThemeColorButtonIconNeutralText = '#3C444C';
export const EdsThemeColorButtonIconNeutralTextHover = '#3C444C';
export const EdsThemeColorButtonIconNeutralTextActive = '#FFFFFF';
export const EdsThemeColorButtonIconSuccessBackground = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonIconSuccessBackgroundHover = '#ECFFF5';
export const EdsThemeColorButtonIconSuccessBackgroundActive = '#007349';
export const EdsThemeColorButtonIconSuccessBorder = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonIconSuccessBorderHover = '#ECFFF5';
export const EdsThemeColorButtonIconSuccessBorderActive = '#007349';
export const EdsThemeColorButtonIconSuccessText = '#007349';
export const EdsThemeColorButtonIconSuccessTextHover = '#007349';
export const EdsThemeColorButtonIconSuccessTextActive = '#FFFFFF';
export const EdsThemeColorButtonIconWarningBackground = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonIconWarningBackgroundHover = '#FFF1E9';
export const EdsThemeColorButtonIconWarningBackgroundActive = '#AC3400';
export const EdsThemeColorButtonIconWarningBorder = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonIconWarningBorderHover = '#FFF1E9';
export const EdsThemeColorButtonIconWarningBorderActive = '#AC3400';
export const EdsThemeColorButtonIconWarningText = '#AC3400';
export const EdsThemeColorButtonIconWarningTextHover = '#AC3400';
export const EdsThemeColorButtonIconWarningTextActive = '#FFFFFF';
export const EdsThemeColorButtonIconErrorBackground = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonIconErrorBackgroundHover = '#FFEBF0';
export const EdsThemeColorButtonIconErrorBackgroundActive = '#BD0044';
export const EdsThemeColorButtonIconErrorBorder = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonIconErrorBorderHover = '#FFEBF0';
export const EdsThemeColorButtonIconErrorBorderActive = '#BD0044';
export const EdsThemeColorButtonIconErrorText = '#BD0044';
export const EdsThemeColorButtonIconErrorTextHover = '#BD0044';
export const EdsThemeColorButtonIconErrorTextActive = '#FFFFFF';
export const EdsThemeColorButtonLinkBrand = '#433BDE';
export const EdsThemeColorButtonLinkBrandHover = '#312B9E';
export const EdsThemeColorButtonLinkBrandActive = '#312B9E';
export const EdsThemeColorButtonLinkNeutral = '#3C444C';
export const EdsThemeColorButtonLinkNeutralHover = '#21272D';
export const EdsThemeColorButtonLinkNeutralActive = '#21272D';
export const EdsThemeColorButtonLinkSuccess = '#007349';
export const EdsThemeColorButtonLinkSuccessHover = '#005939';
export const EdsThemeColorButtonLinkSuccessActive = '#005939';
export const EdsThemeColorButtonLinkWarning = '#AC3400';
export const EdsThemeColorButtonLinkWarningHover = '#852800';
export const EdsThemeColorButtonLinkWarningActive = '#852800';
export const EdsThemeColorButtonLinkError = '#BD0044';
export const EdsThemeColorButtonLinkErrorHover = '#8F0134';
export const EdsThemeColorButtonLinkErrorActive = '#8F0134';
export const EdsThemeColorFocusRing = '#766FFD';
export const EdsThemeColorFocusRingInverted = '#FFFFFF';
export const EdsThemeColorFormBorder = '#CAD1D8';
export const EdsThemeColorFormBorderHover = '#838C95';
export const EdsThemeColorFormBackground = '#FFFFFF';
export const EdsThemeColorFormBackgroundHover = '#F3F3F3';
export const EdsThemeColorFormLabel = '#21272D';
export const EdsThemeColorTextHighlightForeground = '#21272D';
export const EdsThemeColorTextHighlightBackground = '#FCFF00';
export const LegacyColorGray50 = '#F8F9FC';
export const LegacyColorGray100 = '#EBEBEC';
export const LegacyColorGray200 = '#D8D8D9';
export const LegacyColorGray300 = '#C5C5C6';
export const LegacyColorGray500 = '#9F9FA0';
export const LegacyColorGray700 = '#78797A';
export const LegacyColorGray1000 = '#3F4041';
export const LegacyColorBlack = '#2C2D2E';
export const LegacyColorRed100 = '#F7DDDD';
export const LegacyColorRed200 = '#F25252';
export const LegacyColorGreen100 = '#E1F0E7';
export const LegacyColorGreen200 = '#6CC188';
export const LegacyColorGreen300 = '#457B57';
export const LegacyColorYellow200 = '#FFC55B';
export const LegacyColorYellow300 = '#A46900';
export const LegacyColorYellow400 = '#644C1F';
export const LegacyColorPurple200 = '#7686D3';
export const LegacyColorPurple300 = '#5761BA';
export const LegacyColorPurple400 = '#32417C';
