export const EdsThemeColorBodyBackground = '#EEE7E4';
export const EdsThemeColorBodyBackgroundInverted = '#383C43';
export const EdsThemeColorBackgroundInput = 'rgba(255, 255, 255, 1)'; // TODO-AH: what is the token to use here?
export const EdsThemeColorBackgroundNeutralDefault = '#FFFFFF';
export const EdsThemeColorBackgroundNeutralDefaultHover = '#EEE7E4';
export const EdsThemeColorBackgroundNeutralSubtle = '#EEE7E4';
export const EdsThemeColorBackgroundNeutralSubtleHover = '#CFC9C7';
export const EdsThemeColorBackgroundNeutralMedium = '#CFC9C7';
export const EdsThemeColorBackgroundNeutralMediumHover = '#C0C4C8';
export const EdsThemeColorBackgroundBrandPrimaryDefault = '#F0F0FC';
export const EdsThemeColorBackgroundBrandPrimarySubtle = '#F0F0FC';
export const EdsThemeColorBackgroundBrandPrimaryStrong = '#6B65E2';
export const EdsThemeColorBackgroundBrandPrimaryStrongHover = '#3E42B1';
export const EdsThemeColorBackgroundUtilityBase0 = 'rgba(255, 255, 255, 1)'; // TODO-AH: what is the token to use here?
export const EdsThemeColorBackgroundUtilityBase1 = '#FFFFFF'; // TODO-AH: this appears to be missing in the spreadsheet
export const EdsThemeColorBackgroundUtilityContainer = 'rgba(255, 255, 255, 1)'; // TODO-AH: what token is this referring to?
export const EdsThemeColorBackgroundUtilityContainerHover = '#F9F3F1'; // TODO-AH: name format does not match the tier 1
export const EdsThemeColorBackgroundUtilityContainerActive = '#EEE7E4';
export const EdsThemeColorBackgroundUtilityOverlayLowEmphasis = '#272625'; // TODO-AH: color-mix with opacity 50%
export const EdsThemeColorBackgroundUtilityOverlayHighEmphasis = '#272625'; // TODO-AH: color-mix with opacity 80%
export const EdsThemeColorBackgroundUtilityNeutralNoEmphasis = 'transparent'; // TODO-AH: what token is this referring to?
export const EdsThemeColorBackgroundUtilityNeutralNoEmphasisHover = '#F9F3F1'; // TODO-AH: name format does not match the tier 1
export const EdsThemeColorBackgroundUtilityNeutralNoEmphasisActive = '#EEE7E4';
export const EdsThemeColorBackgroundUtilityNeutralLowEmphasis = '#F9F3F1'; // TODO-AH: name format does not match the tier 1
export const EdsThemeColorBackgroundUtilityNeutralLowEmphasisHover = '#EEE7E4';
export const EdsThemeColorBackgroundUtilityNeutralLowEmphasisActive = '#DFD9D6';
export const EdsThemeColorBackgroundUtilityNeutralHighEmphasis = '#6C6967';
export const EdsThemeColorBackgroundUtilityNeutralHighEmphasisHover = '#565352';
export const EdsThemeColorBackgroundUtilityNeutralHighEmphasisActive =
  '#3F3E3D';
export const EdsThemeColorBackgroundUtilityInteractiveNoEmphasis =
  'transparent'; // TODO-AH: what token is this referring to?
export const EdsThemeColorBackgroundUtilityInteractiveNoEmphasisHover =
  '#EAF4FF'; // TODO-AH: name format does not match the tier 1
export const EdsThemeColorBackgroundUtilityInteractiveNoEmphasisActive =
  '#CEE6FF';
export const EdsThemeColorBackgroundUtilityInteractiveLowEmphasis = '#EAF4FF'; // TODO-AH: name format does not match the tier 1
export const EdsThemeColorBackgroundUtilityInteractiveLowEmphasisHover =
  '#CEE6FF';
export const EdsThemeColorBackgroundUtilityInteractiveLowEmphasisActive =
  '#B5DAFF';
export const EdsThemeColorBackgroundUtilityInteractiveHighEmphasis = '#0F2163';
export const EdsThemeColorBackgroundUtilityInteractiveHighEmphasisHover =
  '#0A164C';
export const EdsThemeColorBackgroundUtilityInteractiveHighEmphasisActive =
  '#060E30';
export const EdsThemeColorBackgroundUtilityCriticalNoEmphasis = 'transparent'; // TODO-AH: what token is this referring to?
export const EdsThemeColorBackgroundUtilityCriticalNoEmphasisHover = 'FCF2F7'; // TODO-AH: name format does not match the tier 1
export const EdsThemeColorBackgroundUtilityCriticalNoEmphasisActive = 'F8DDEA';
export const EdsThemeColorBackgroundUtilityCriticalLowEmphasis = 'FCF2F7'; // TODO-AH: name format does not match the tier 1
export const EdsThemeColorBackgroundUtilityCriticalLowEmphasisHover = 'F8DDEA';
export const EdsThemeColorBackgroundUtilityCriticalLowEmphasisActive = 'F5CCE0';
export const EdsThemeColorBackgroundUtilityCriticalHighEmphasis = '9F1C55';
export const EdsThemeColorBackgroundUtilityCriticalHighEmphasisHover = '760C35';
export const EdsThemeColorBackgroundUtilityCriticalHighEmphasisActive =
  '620424';
export const EdsThemeColorBackgroundUtilityFavorableLowEmphasis = '#E6F5ED'; // TODO-AH: name format does not match the tier 1
export const EdsThemeColorBackgroundUtilityFavorableLowEmphasisHover =
  '#D0EDDD';
export const EdsThemeColorBackgroundUtilityFavorableLowEmphasisActive =
  '#B3E1C7';
export const EdsThemeColorBackgroundUtilityFavorableHighEmphasis = '#367759';
export const EdsThemeColorBackgroundUtilityFavorableHighEmphasisHover =
  '#225E43';
export const EdsThemeColorBackgroundUtilityFavorableHighEmphasisActive =
  '#13462F';
export const EdsThemeColorBackgroundUtilityWarningLowEmphasis = '#FDF3D3'; // TODO-AH: name format does not match the tier 1
export const EdsThemeColorBackgroundUtilityWarningLowEmphasisHover = '#FBE8AB';
export const EdsThemeColorBackgroundUtilityWarningLowEmphasisActive = '#F9DA78';
export const EdsThemeColorBackgroundUtilityInformationLowEmphasis = '#EAF4FF'; // TODO-AH: name format does not match the tier 1
export const EdsThemeColorBackgroundUtilityInformationLowEmphasisHover =
  '#CEE6FF';
export const EdsThemeColorBackgroundUtilityInformationLowEmphasisActive =
  '#B5DAFF';
export const EdsThemeColorBackgroundUtilityDisabledNoEmphasis = 'transparent'; // TODO-AH: this appears to be missing in the spreadsheet
export const EdsThemeColorBackgroundUtilityDisabledLowEmphasis = '#EEE7E4';
export const EdsThemeColorBackgroundUtilityDisabledMediumEmphasis = '#CFC9C7';
export const EdsThemeColorBackgroundUtilityInverseNoEmphasis = 'transparent'; // TODO-AH: this appears to be missing in the spreadsheet
export const EdsThemeColorBackgroundUtilityInverseNoEmphasisHover =
  'rgba(255,255,255, 0.2)'; // TODO-AH: missing token to color-mix with opacity 20%
export const EdsThemeColorBackgroundUtilityInverseNoEmphasisActive =
  'rgba(255, 255, 255, 0.3)'; // TODO-AH: missing token to color-mix with opacity 20%
export const EdsThemeColorBackgroundUtilityInverseHighEmphasis =
  'rgba(255, 255, 255, 1)'; // TODO-AH: missing token to color-mix with opacity 100%
export const EdsThemeColorBackgroundUtilityInverseHighEmphasisHover = '#F9F3F1'; // TODO-AH: name format does not match the tier 1
export const EdsThemeColorBackgroundUtilityInverseHighEmphasisActive =
  '#EEE7E4';
export const EdsThemeColorBackgroundUtilityInverseDisabled =
  'rgba(255, 255, 255, 0.5)'; // TODO-AH: missing token to color-mix with opacity 50%
export const EdsThemeColorBackgroundUtilitySuccess = '#ECFFF5'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsThemeColorBackgroundUtilityError = '#FFF0F4'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsThemeColorBackgroundGradeCompleteDefault = '#008656'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsThemeColorBackgroundGradeCompleteSubtle = '#ECFFF5'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsThemeColorBackgroundGradeReviseDefault = '#F7BE2D'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsThemeColorBackgroundGradeReviseSubtle = '#FDF1D0'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsThemeColorBackgroundGradeStopDefault = '#D41E52'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsThemeColorBackgroundGradeStopSubtle = '#FFF0F4'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsThemeColorBackgroundDisabled = '#C0C4C8';
export const EdsThemeColorBorderNeutralSubtle = '#CFC9C7';
export const EdsThemeColorBorderNeutralSubtleHover = '#C0C4C8';
export const EdsThemeColorBorderNeutralDefault = '#C0C4C8';
export const EdsThemeColorBorderNeutralDefaultHover = '#999EA3';
export const EdsThemeColorBorderNeutralStrong = '#999EA3';
export const EdsThemeColorBorderNeutralStrongHover = '#878C90';
export const EdsThemeColorBorderBrandPrimarySubtle = '#E0E0F9';
export const EdsThemeColorBorderBrandPrimaryDefault =
  'var(--eds-theme-color-border-brand-primary)';
export const EdsThemeColorBorderBrandPrimary = '#C4C1F3'; // @deprecated This token is deprecated. Please use eds-theme-color-border-brand-primary-default instead
export const EdsThemeColorBorderBrandPrimaryStrong = '#A6A3EE';
export const EdsThemeColorBorderUtilityNeutralLowEmphasis = '#CFC9C7';
export const EdsThemeColorBorderUtilityNeutralLowEmphasisHover = '#BEB8B6';
export const EdsThemeColorBorderUtilityNeutralLowEmphasisActive = '#A09C9A';
export const EdsThemeColorBorderUtilityNeutralMediumEmphasis = '#868281';
export const EdsThemeColorBorderUtilityNeutralMediumEmphasisHover = '#6C6967';
export const EdsThemeColorBorderUtilityNeutralMediumEmphasisActive = '#565352';
export const EdsThemeColorBorderUtilityNeutralHighEmphasis = '#272625';
export const EdsThemeColorBorderUtilityNeutralHighEmphasisHover = '#1A1919';
export const EdsThemeColorBorderUtilityNeutralHighEmphasisActive = '#0F0F0F';
export const EdsThemeColorBorderUtilityInteractive = '#0F2163';
export const EdsThemeColorBorderUtilityInteractiveHover = '#0A164C';
export const EdsThemeColorBorderUtilityInteractiveActive = '#060E30';
export const EdsThemeColorBorderUtilityCritical = '9F1C55';
export const EdsThemeColorBorderUtilityCriticalHover = '760C35';
export const EdsThemeColorBorderUtilityCriticalActive = '620424';
export const EdsThemeColorBorderUtilityFavorable = '#367759';
export const EdsThemeColorBorderUtilityFavorableHover = '#225E43';
export const EdsThemeColorBorderUtilityFavorableActive = '#13462F';
export const EdsThemeColorBorderUtilityWarning = '#876701';
export const EdsThemeColorBorderUtilityWarningHover = '#695001';
export const EdsThemeColorBorderUtilityWarningActive = '#4D3A01';
export const EdsThemeColorBorderUtilityWarningSubtle = '#FFCBA5'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsThemeColorBorderUtilityWarningDefault = '#FFAF76'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsThemeColorBorderUtilityWarningStrong = '#F6924A'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsThemeColorBorderUtilityInformational = '#3165D2';
export const EdsThemeColorBorderUtilityInformationalHover = '#254EAC';
export const EdsThemeColorBorderUtilityInformationalActive = '#1B3889';
export const EdsThemeColorBorderUtilityDisabled = '#A09C9A';
export const EdsThemeColorBorderUtilityFocus = '#3165D2';
export const EdsThemeColorBorderUtilityInverse = 'rgba(255, 255, 255, 1)'; // TODO-AH: missing token to color-mix with opacity 100%
export const EdsThemeColorBorderUtilityInverseDisabled =
  'rgba(255, 255, 255, 0.5)'; // TODO-AH: missing token to color-mix with opacity 50%
export const EdsThemeColorBorderUtilitySuccessSubtle = '#B7E9CE'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsThemeColorBorderUtilitySuccessDefault = '#8FDCB3'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsThemeColorBorderUtilitySuccessStrong = '#59C88C'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsThemeColorBorderUtilityErrorSubtle = '#FFCBD7';
export const EdsThemeColorBorderUtilityErrorDefault = '#FB90B0';
export const EdsThemeColorBorderUtilityErrorStrong = '#F76C96';
export const EdsThemeColorBorderGradeComplete = '#8FDCB3'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsThemeColorBorderGradeReviseSubtle = '#FFEBB3'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsThemeColorBorderGradeReviseDefault = '#FFDD80'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsThemeColorBorderGradeReviseStrong = '#F7BE2D'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsThemeColorBorderGradeStop = '#FB90B0'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsThemeColorBorderDisabled = '#C0C4C8';
export const EdsThemeColorButtonPrimaryBrandBackground = '#6B65E2';
export const EdsThemeColorButtonPrimaryBrandBackgroundHover = '#5751D2';
export const EdsThemeColorButtonPrimaryBrandBackgroundActive = '#3E42B1';
export const EdsThemeColorButtonPrimaryBrandBorder = '#6B65E2';
export const EdsThemeColorButtonPrimaryBrandBorderHover = '#5751D2';
export const EdsThemeColorButtonPrimaryBrandBorderActive = '#3E42B1';
export const EdsThemeColorButtonPrimaryBrandText = '#FFFFFF';
export const EdsThemeColorButtonPrimaryBrandTextHover = '#FFFFFF';
export const EdsThemeColorButtonPrimaryBrandTextActive = '#FFFFFF';
export const EdsThemeColorButtonPrimaryErrorBackground = '#D41E52';
export const EdsThemeColorButtonPrimaryErrorBackgroundHover = '#BD0044';
export const EdsThemeColorButtonPrimaryErrorBackgroundActive = '#8F0134';
export const EdsThemeColorButtonPrimaryErrorBorder = '#D41E52';
export const EdsThemeColorButtonPrimaryErrorBorderHover = '#BD0044';
export const EdsThemeColorButtonPrimaryErrorBorderActive = '#8F0134';
export const EdsThemeColorButtonPrimaryErrorText = '#FFFFFF';
export const EdsThemeColorButtonPrimaryErrorTextHover = '#FFFFFF';
export const EdsThemeColorButtonPrimaryErrorTextActive = '#FFFFFF';
export const EdsThemeColorButtonSecondaryBrandBackground = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonSecondaryBrandBackgroundHover = '#5751D2';
export const EdsThemeColorButtonSecondaryBrandBackgroundActive = '#3E42B1';
export const EdsThemeColorButtonSecondaryBrandBorder = '#6B65E2';
export const EdsThemeColorButtonSecondaryBrandBorderHover = '#5751D2';
export const EdsThemeColorButtonSecondaryBrandBorderActive = '#3E42B1';
export const EdsThemeColorButtonSecondaryBrandText = '#5751D2';
export const EdsThemeColorButtonSecondaryBrandTextHover = '#FFFFFF';
export const EdsThemeColorButtonSecondaryBrandTextActive = '#FFFFFF';
export const EdsThemeColorButtonSecondaryBrandIcon = '#6B65E2';
export const EdsThemeColorButtonSecondaryBrandIconHover = '#FFFFFF';
export const EdsThemeColorButtonSecondaryBrandIconActive = '#FFFFFF';
export const EdsThemeColorButtonSecondaryNeutralBackground = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonSecondaryNeutralBackgroundHover = '#CFC9C7';
export const EdsThemeColorButtonSecondaryNeutralBackgroundActive = '#383C43';
export const EdsThemeColorButtonSecondaryNeutralBorder = '#5D6369';
export const EdsThemeColorButtonSecondaryNeutralBorderHover = '#5D6369';
export const EdsThemeColorButtonSecondaryNeutralBorderActive = '#383C43';
export const EdsThemeColorButtonSecondaryNeutralText = '#5D6369';
export const EdsThemeColorButtonSecondaryNeutralTextHover = '#5D6369';
export const EdsThemeColorButtonSecondaryNeutralTextActive = '#FFFFFF';
export const EdsThemeColorButtonSecondaryNeutralIcon = '#999EA3';
export const EdsThemeColorButtonSecondaryNeutralIconHover = '#999EA3';
export const EdsThemeColorButtonSecondaryNeutralIconActive = '#FFFFFF';
export const EdsThemeColorButtonSecondarySuccessBackground = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonSecondarySuccessBackgroundHover = '#007249';
export const EdsThemeColorButtonSecondarySuccessBackgroundActive = '#005939';
export const EdsThemeColorButtonSecondarySuccessBorder = '#008656';
export const EdsThemeColorButtonSecondarySuccessBorderHover = '#007249';
export const EdsThemeColorButtonSecondarySuccessBorderActive = '#005939';
export const EdsThemeColorButtonSecondarySuccessText = '#007249';
export const EdsThemeColorButtonSecondarySuccessTextHover = '#FFFFFF';
export const EdsThemeColorButtonSecondarySuccessTextActive = '#FFFFFF';
export const EdsThemeColorButtonSecondarySuccessIcon = '#008656';
export const EdsThemeColorButtonSecondarySuccessIconHover = '#FFFFFF';
export const EdsThemeColorButtonSecondarySuccessIconActive = '#FFFFFF';
export const EdsThemeColorButtonSecondaryWarningBackground = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonSecondaryWarningBackgroundHover = '#AC3400';
export const EdsThemeColorButtonSecondaryWarningBackgroundActive = '#842800';
export const EdsThemeColorButtonSecondaryWarningBorder = '#C64600';
export const EdsThemeColorButtonSecondaryWarningBorderHover = '#AC3400';
export const EdsThemeColorButtonSecondaryWarningBorderActive = '#842800';
export const EdsThemeColorButtonSecondaryWarningText = '#AC3400';
export const EdsThemeColorButtonSecondaryWarningTextHover = '#FFFFFF';
export const EdsThemeColorButtonSecondaryWarningTextActive = '#FFFFFF';
export const EdsThemeColorButtonSecondaryWarningIcon = '#C64600';
export const EdsThemeColorButtonSecondaryWarningIconHover = '#FFFFFF';
export const EdsThemeColorButtonSecondaryWarningIconActive = '#FFFFFF';
export const EdsThemeColorButtonSecondaryErrorBackground = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonSecondaryErrorBackgroundHover = '#BD0044';
export const EdsThemeColorButtonSecondaryErrorBackgroundActive = '#8F0134';
export const EdsThemeColorButtonSecondaryErrorBorder = '#D41E52';
export const EdsThemeColorButtonSecondaryErrorBorderHover = '#BD0044';
export const EdsThemeColorButtonSecondaryErrorBorderActive = '#8F0134';
export const EdsThemeColorButtonSecondaryErrorText = '#BD0044';
export const EdsThemeColorButtonSecondaryErrorTextHover = '#FFFFFF';
export const EdsThemeColorButtonSecondaryErrorTextActive = '#FFFFFF';
export const EdsThemeColorButtonSecondaryErrorIcon = '#D41E52';
export const EdsThemeColorButtonSecondaryErrorIconHover = '#FFFFFF';
export const EdsThemeColorButtonSecondaryErrorIconActive = '#FFFFFF';
export const EdsThemeColorButtonIconBrand = '#6B65E2';
export const EdsThemeColorButtonIconBrandHover = '#6B65E2';
export const EdsThemeColorButtonIconBrandActive = '#FFFFFF';
export const EdsThemeColorButtonIconBrandBackground = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonIconBrandBackgroundHover = '#E0E0F9';
export const EdsThemeColorButtonIconBrandBackgroundActive = '#5751D2';
export const EdsThemeColorButtonIconBrandBorder = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonIconBrandBorderHover = '#E0E0F9';
export const EdsThemeColorButtonIconBrandBorderActive = '#5751D2';
export const EdsThemeColorButtonIconBrandText = '#5751D2';
export const EdsThemeColorButtonIconBrandTextHover = '#5751D2';
export const EdsThemeColorButtonIconBrandTextActive = '#FFFFFF';
export const EdsThemeColorButtonIconNeutral = '#5D6369';
export const EdsThemeColorButtonIconNeutralHover = '#5D6369';
export const EdsThemeColorButtonIconNeutralActive = '#FFFFFF';
export const EdsThemeColorButtonIconNeutralBackground = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonIconNeutralBackgroundHover = '#CFC9C7';
export const EdsThemeColorButtonIconNeutralBackgroundActive = '#5D6369';
export const EdsThemeColorButtonIconNeutralBorder = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonIconNeutralBorderHover = '#CFC9C7';
export const EdsThemeColorButtonIconNeutralBorderActive = '#5D6369';
export const EdsThemeColorButtonIconNeutralText = '#5D6369';
export const EdsThemeColorButtonIconNeutralTextHover = '#5D6369';
export const EdsThemeColorButtonIconNeutralTextActive = '#FFFFFF';
export const EdsThemeColorButtonIconSuccess = '#008656';
export const EdsThemeColorButtonIconSuccessHover = '#008656';
export const EdsThemeColorButtonIconSuccessActive = '#FFFFFF';
export const EdsThemeColorButtonIconSuccessBackground = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonIconSuccessBackgroundHover = '#B7E9CE';
export const EdsThemeColorButtonIconSuccessBackgroundActive = '#007249';
export const EdsThemeColorButtonIconSuccessBorder = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonIconSuccessBorderHover = '#B7E9CE';
export const EdsThemeColorButtonIconSuccessBorderActive = '#007249';
export const EdsThemeColorButtonIconSuccessText = '#007249';
export const EdsThemeColorButtonIconSuccessTextHover = '#007249';
export const EdsThemeColorButtonIconSuccessTextActive = '#FFFFFF';
export const EdsThemeColorButtonIconWarning = '#C64600';
export const EdsThemeColorButtonIconWarningHover = '#C64600';
export const EdsThemeColorButtonIconWarningActive = '#FFFFFF';
export const EdsThemeColorButtonIconWarningBackground = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonIconWarningBackgroundHover = '#FFF1E9';
export const EdsThemeColorButtonIconWarningBackgroundActive = '#AC3400';
export const EdsThemeColorButtonIconWarningBorder = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonIconWarningBorderHover = '#FFF1E9';
export const EdsThemeColorButtonIconWarningBorderActive = '#AC3400';
export const EdsThemeColorButtonIconWarningText = '#AC3400';
export const EdsThemeColorButtonIconWarningTextHover = '#AC3400';
export const EdsThemeColorButtonIconWarningTextActive = '#FFFFFF';
export const EdsThemeColorButtonIconError = '#D41E52';
export const EdsThemeColorButtonIconErrorHover = '#D41E52';
export const EdsThemeColorButtonIconErrorActive = '#FFFFFF';
export const EdsThemeColorButtonIconErrorBackground = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonIconErrorBackgroundHover = '#FFCBD7';
export const EdsThemeColorButtonIconErrorBackgroundActive = '#BD0044';
export const EdsThemeColorButtonIconErrorBorder = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonIconErrorBorderHover = '#FFCBD7';
export const EdsThemeColorButtonIconErrorBorderActive = '#BD0044';
export const EdsThemeColorButtonIconErrorText = '#BD0044';
export const EdsThemeColorButtonIconErrorTextHover = '#BD0044';
export const EdsThemeColorButtonIconErrorTextActive = '#FFFFFF';
export const EdsThemeColorCheckboxBrandBackground = '#8984E8';
export const EdsThemeColorDataBarBackground = '#EEE7E4'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsThemeColorDataBarBorder = '#C0C4C8'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsThemeColorFocusRing = '#6B65E2';
export const EdsThemeColorFocusRingInverted = '#FFFFFF';
export const EdsThemeColorFormBorder = '#878C90';
export const EdsThemeColorFormBorderHover = '#333231';
export const EdsThemeColorFormBackground = '#FFFFFF';
export const EdsThemeColorFormBackgroundHover = '#EEE7E4';
export const EdsThemeColorFormLabel = '#383C43';
export const EdsThemeColorIconNeutralDefault = '#5D6369';
export const EdsThemeColorIconNeutralDefaultInverse = '#FFFFFF';
export const EdsThemeColorIconNeutralDefaultHover = '#383C43';
export const EdsThemeColorIconNeutralStrong = '#383C43';
export const EdsThemeColorIconNeutralStrongHover = '#333231';
export const EdsThemeColorIconNeutralSubtle = '#878C90';
export const EdsThemeColorIconNeutralSubtleHover = '#5D6369';
export const EdsThemeColorIconLinkDefault = '#6B65E2';
export const EdsThemeColorIconLinkDefaultHover = '#5751D2';
export const EdsThemeColorIconBrandPrimary = '#8984E8';
export const EdsThemeColorIconBrandPrimaryHover = '#6B65E2';
export const EdsThemeColorIconUtilitySuccess = '#00A56A';
export const EdsThemeColorIconUtilitySuccessHover = '#008656';
export const EdsThemeColorIconUtilityWarning = '#E06B00';
export const EdsThemeColorIconUtilityWarningHover = '#C64600';
export const EdsThemeColorIconUtilityError = '#F1497B';
export const EdsThemeColorIconUtilityErrorHover = '#D41E52';
export const EdsThemeColorIconGradeComplete = '#00A56A'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsThemeColorIconGradeCompleteHover = '#00A56A'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsThemeColorIconGradeRevise = '#333231'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsThemeColorIconGradeReviseHover = '#161B1F'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsThemeColorIconGradeStop = '#F1497B'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsThemeColorIconGradeStopHover = '#D41E52'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsThemeColorIconDisabled = '#C0C4C8';
export const EdsThemeColorLinkBrandText =
  'var(--eds-theme-color-text-neutral-strong)';
export const EdsThemeColorLinkBrandTextHover =
  'var(--eds-theme-color-text-brand-default)';
export const EdsThemeColorLinkBrandTextFocus =
  'var(--eds-theme-color-text-neutral-default-inverse)';
export const EdsThemeColorLinkBrandTextDecoration =
  'var(--eds-theme-color-text-brand-default)';
export const EdsThemeColorLinkBrandTextDecorationHover =
  'var(--eds-theme-color-text-brand-default)';
export const EdsThemeColorLinkBrandTextDecorationFocus =
  'var(--eds-theme-color-text-neutral-default-inverse)';
export const EdsThemeColorLinkBrandBackgroundFocus =
  'var(--eds-theme-color-text-brand-default)';
export const EdsThemeColorLinkNeutralText =
  'var(--eds-theme-color-text-neutral-strong)';
export const EdsThemeColorLinkNeutralTextHover =
  'var(--eds-theme-color-text-brand-default)';
export const EdsThemeColorLinkNeutralTextFocus =
  'var(--eds-theme-color-text-neutral-default-inverse)';
export const EdsThemeColorLinkNeutralTextDecoration =
  'var(--eds-theme-color-text-neutral-default)';
export const EdsThemeColorLinkNeutralTextDecorationHover =
  'var(--eds-theme-color-text-brand-default)';
export const EdsThemeColorLinkNeutralTextDecorationFocus =
  'var(--eds-theme-color-text-neutral-default-inverse)';
export const EdsThemeColorLinkNeutralBackgroundFocus =
  'var(--eds-theme-color-text-neutral-default)';
export const EdsThemeColorModalBrandHeaderBackground = '#8984E8';
export const EdsThemeColorProgressBarBackground = '#CFC9C7';
export const EdsThemeColorProgressBarBorder = '#CFC9C7';
export const EdsThemeColorRadioBrandBackground = '#8984E8';
export const EdsThemeColorTextNeutralDefault = '#383C43';
export const EdsThemeColorTextNeutralDefaultInverse = '#FFFFFF';
export const EdsThemeColorTextNeutralStrong = '#333231';
export const EdsThemeColorTextNeutralSubtle = '#5D6369';
export const EdsThemeColorTextUtilityNeutralPrimary = '#272625';
export const EdsThemeColorTextUtilityNeutralPrimaryHover = '#1A1919';
export const EdsThemeColorTextUtilityNeutralPrimaryActive = '#0F0F0F';
export const EdsThemeColorTextUtilityNeutralSecondary = '#6C6967';
export const EdsThemeColorTextUtilityNeutralSecondaryHover = '#565352';
export const EdsThemeColorTextUtilityNeutralSecondaryActive = '#3F3E3D';
export const EdsThemeColorTextUtilityInteractivePrimary = '#0F2163';
export const EdsThemeColorTextUtilityInteractivePrimaryHover = '#0A164C';
export const EdsThemeColorTextUtilityInteractivePrimaryActive = '#060E30';
export const EdsThemeColorTextUtilityInteractiveSecondary = '#3165D2';
export const EdsThemeColorTextUtilityInteractiveSecondaryHover = '#254EAC';
export const EdsThemeColorTextUtilityInteractiveSecondaryActive = '#1B3889';
export const EdsThemeColorTextUtilityInteractiveVisited = '#8A50A7';
export const EdsThemeColorTextUtilityCritical = '9F1C55';
export const EdsThemeColorTextUtilityCriticalHover = '760C35';
export const EdsThemeColorTextUtilityCriticalActive = '620424';
export const EdsThemeColorTextUtilityFavorable = '#367759';
export const EdsThemeColorTextUtilityFavorableHover = '#225E43';
export const EdsThemeColorTextUtilityFavorableActive = '#13462F';
export const EdsThemeColorTextUtilityWarning = '#876701';
export const EdsThemeColorTextUtilityWarningHover = '#695001';
export const EdsThemeColorTextUtilityWarningActive = '#4D3A01';
export const EdsThemeColorTextUtilityInformational = '#3165D2';
export const EdsThemeColorTextUtilityInformationalHover = '#254EAC';
export const EdsThemeColorTextUtilityInformationalActive = '#1B3889';
export const EdsThemeColorTextUtilityDisabledPrimary = '#A09C9A';
export const EdsThemeColorTextUtilityDisabledSecondary = '#CFC9C7';
export const EdsThemeColorTextUtilityInverse = 'rgba(255, 255, 255, 1)'; // TODO-AH: what token is this referring to?
export const EdsThemeColorTextUtilityInverseDisabled =
  'rgba(255, 255, 255, 0.5)'; // TODO-AH: what token is this referring to?
export const EdsThemeColorTextUtilityPlaceholder = '#6C6967';
export const EdsThemeColorTextUtilitySuccess = '#007249'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsThemeColorTextUtilityError = '#BD0044';
export const EdsThemeColorTextGradeComplete = '#007249'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsThemeColorTextGradeRevise = '#333231'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsThemeColorTextGradeStop = '#BD0044'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsThemeColorTextDisabled = '#C0C4C8';
export const EdsThemeColorTextBrandDefault =
  'var(--eds-theme-color-text-brand-primary)';
export const EdsThemeColorTextBrandPrimary = '#5751D2'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS. Please use eds-theme-color-text-brand-default instead.
export const EdsThemeColorTextHighlightForeground = '#333231';
export const EdsThemeColorTextHighlightBackground = '#FDF1D0';
export const EdsThemeColorToggleOnBackground =
  'var(--eds-theme-color-background-brand-primary-strong)';
export const EdsThemeColorToggleOffBackground =
  'var(--eds-theme-color-icon-neutral-subtle)';
export const EdsThemeColorToggleDisabledBackground =
  'var(--eds-theme-color-icon-disabled)';
export const EdsThemeColorToggleDisabledText =
  'var(--eds-theme-color-text-disabled)';
export const EdsThemeColorTogglePrimaryText =
  'var(--eds-theme-color-text-neutral-default)';
export const EdsThemeColorToggleThumb =
  'var(--eds-theme-color-text-neutral-default-inverse)';
export const EdsThemeColorTransparentBlack0 = 'rgba(0, 0, 0, 0)'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsThemeColorTransparentBlack30 = 'rgba(0, 0, 0, .3)'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsThemeColorTransparentWhite0 = 'rgba(255, 255, 255, 0)'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorBrandGrape100 = '#F0F0FC'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorBrandGrape200 = '#E0E0F9'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorBrandGrape300 = '#C4C1F3'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorBrandGrape400 = '#A6A3EE'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorBrandGrape500 = '#8984E8'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorBrandGrape600 = '#6B65E2'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorBrandGrape700 = '#5751D2'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorBrandGrape800 = '#3E42B1'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorNeutral100 = '#EEE7E4';
export const EdsColorNeutral150 = '#DFD9D6';
export const EdsColorNeutral200 = '#CFC9C7';
export const EdsColorNeutral250 = '#BEB8B6';
export const EdsColorNeutral300 = '#C0C4C8'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorNeutral350 = '#A09C9A';
export const EdsColorNeutral400 = '#999EA3'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorNeutral450 = '#868281';
export const EdsColorNeutral500 = '#878C90'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorNeutral550 = '#6C6967';
export const EdsColorNeutral600 = '#5D6369'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorNeutral650 = '#565352';
export const EdsColorNeutral700 = '#383C43'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorNeutral750 = '#3F3E3D';
export const EdsColorNeutral800 = '#333231';
export const EdsColorNeutral850 = '#272625';
export const EdsColorNeutral900 = '#1A1919';
export const EdsColorNeutral950 = '#0F0F0F';
export const EdsColorNeutralWhite = '#FFFFFF'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorNeutral025 = '#FFFFFF'; // TODO-AH: inserting missing value
export const EdsColorNeutral050 = '#F9F3F1';
export const EdsColorNeutralBlack = '#161B1F'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorRed100 = 'F8DDEA';
export const EdsColorRed150 = 'F5CCE0';
export const EdsColorRed200 = 'F1B5D2';
export const EdsColorRed250 = 'EC9EC3';
export const EdsColorRed350 = 'E67EB0';
export const EdsColorRed450 = 'DB458D';
export const EdsColorRed550 = 'C62B73';
export const EdsColorRed650 = '9F1C55';
export const EdsColorRed750 = '760C35';
export const EdsColorRed800 = '620424';
export const EdsColorRed850 = '4D0118';
export const EdsColorRed900 = '350110';
export const EdsColorRed950 = '23010B';
export const EdsColorRed050 = 'FCF2F7';
export const EdsColorOrange100 = '#FFDCCA';
export const EdsColorOrange150 = '#FFC7AB';
export const EdsColorOrange200 = '#FFB38D';
export const EdsColorOrange250 = '#FFA070';
export const EdsColorOrange350 = '#E87F4A';
export const EdsColorOrange450 = '#D0622C';
export const EdsColorOrange550 = '#B8470F';
export const EdsColorOrange650 = '#92380C';
export const EdsColorOrange750 = '#672808';
export const EdsColorOrange800 = '#532006';
export const EdsColorOrange850 = '#401805';
export const EdsColorOrange900 = '#2B1003';
export const EdsColorOrange950 = '#1B0A02';
export const EdsColorOrange050 = '#FFEEE5';
export const EdsColorYellow100 = '#FBE8AB';
export const EdsColorYellow150 = '#F9DA78';
export const EdsColorYellow200 = '#F1CA53';
export const EdsColorYellow250 = '#E7B724';
export const EdsColorYellow350 = '#C4970C';
export const EdsColorYellow450 = '#A57D01';
export const EdsColorYellow550 = '#876701';
export const EdsColorYellow650 = '#695001';
export const EdsColorYellow750 = '#4D3A01';
export const EdsColorYellow800 = '#392B01';
export const EdsColorYellow850 = '#2B2001';
export const EdsColorYellow900 = '#1E1701';
export const EdsColorYellow950 = '#130E01';
export const EdsColorYellow050 = '#FDF3D3';
export const EdsColorGreen100 = '#D0EDDD';
export const EdsColorGreen150 = '#B3E1C7';
export const EdsColorGreen200 = '#95D5B1';
export const EdsColorGreen250 = '#74C899';
export const EdsColorGreen350 = '#57B083';
export const EdsColorGreen450 = '#3F926D';
export const EdsColorGreen550 = '#367759';
export const EdsColorGreen650 = '#225E43';
export const EdsColorGreen750 = '#13462F';
export const EdsColorGreen800 = '#0E3423';
export const EdsColorGreen850 = '#0A271A';
export const EdsColorGreen900 = '#071B12';
export const EdsColorGreen950 = '#05120C';
export const EdsColorGreen050 = '#E6F5ED';
export const EdsColorBlue100 = '#CEE6FF';
export const EdsColorBlue150 = '#B5DAFF';
export const EdsColorBlue200 = '#99CCFF';
export const EdsColorBlue250 = '#85BAFB';
export const EdsColorBlue350 = '#6199F3';
export const EdsColorBlue450 = '#437EED';
export const EdsColorBlue550 = '#3165D2';
export const EdsColorBlue650 = '#254EAC';
export const EdsColorBlue750 = '#1B3889';
export const EdsColorBlue800 = '#152D76';
export const EdsColorBlue850 = '#0F2163';
export const EdsColorBlue900 = '#0A164C';
export const EdsColorBlue950 = '#060E30';
export const EdsColorBlue050 = '#EAF4FF';
export const EdsColorPurple100 = '#F3E5FA';
export const EdsColorPurple150 = '#EAD1F6';
export const EdsColorPurple200 = '#E0BAF2';
export const EdsColorPurple250 = '#D5A2EE';
export const EdsColorPurple350 = '#C580E7';
export const EdsColorPurple450 = '#A765C7';
export const EdsColorPurple550 = '#8A50A7';
export const EdsColorPurple650 = '#6E3A88';
export const EdsColorPurple750 = '#562D69';
export const EdsColorPurple800 = '#452455';
export const EdsColorPurple850 = '#311A3C';
export const EdsColorPurple900 = '#25142E';
export const EdsColorPurple950 = '#190D1E';
export const EdsColorPurple050 = '#FBF5FD';
export const EdsColorOpacity10 = '.10';
export const EdsColorOpacity20 = '.20';
export const EdsColorOpacity30 = '.30';
export const EdsColorOpacity40 = '.40';
export const EdsColorOpacity50 = '.50';
export const EdsColorOpacity60 = '.60';
export const EdsColorOpacity70 = '.60';
export const EdsColorOpacity80 = '.80';
export const EdsColorOtherMint100 = '#ECFFF5'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorOtherMint200 = '#B7E9CE'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorOtherMint300 = '#8FDCB3'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorOtherMint400 = '#59C88C'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorOtherMint500 = '#00A56A'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorOtherMint600 = '#008656'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorOtherMint700 = '#007249'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorOtherMint800 = '#005939'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorOtherYellow100 = '#FDF1D0'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorOtherYellow200 = '#FFEBB3'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorOtherYellow300 = '#FFDD80'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorOtherYellow400 = '#F7BE2D'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorOtherYellow500 = '#D18400'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorOtherYellow600 = '#BF7300'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorOtherYellow700 = '#9E5B03'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorOtherYellow800 = '#854C03'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorOtherLemon = '#F5FF8F'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorOtherEraser = '#F3DCE2'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorOtherOrange100 = '#FFF1E9'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorOtherOrange200 = '#FFCBA5'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorOtherOrange300 = '#FFAF76'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorOtherOrange400 = '#F6924A'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorOtherOrange500 = '#E06B00'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorOtherOrange600 = '#C64600'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorOtherOrange700 = '#AC3400'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorOtherOrange800 = '#842800'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorOtherRuby100 = '#FFF0F4'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorOtherRuby200 = '#FFCBD7'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorOtherRuby300 = '#FB90B0'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorOtherRuby400 = '#F76C96'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorOtherRuby500 = '#F1497B'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorOtherRuby600 = '#D41E52'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorOtherRuby700 = '#BD0044'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
export const EdsColorOtherRuby800 = '#8F0134'; // @deprecated This should not be used in code or design. It will be removed in a future version of EDS.
