export const EdsColorBrandGrape100 = '#F0F0FC';
export const EdsColorBrandGrape200 = '#E0E0F9';
export const EdsColorBrandGrape300 = '#C4C1F3';
export const EdsColorBrandGrape400 = '#A6A3EE';
export const EdsColorBrandGrape500 = '#8984E8';
export const EdsColorBrandGrape600 = '#6B65E2';
export const EdsColorBrandGrape700 = '#5751D2';
export const EdsColorBrandGrape800 = '#3E42B1';
export const EdsColorNeutral100 = '#F4F6F8';
export const EdsColorNeutral200 = '#E7E8EA';
export const EdsColorNeutral300 = '#C0C4C8';
export const EdsColorNeutral400 = '#999EA3';
export const EdsColorNeutral500 = '#878C90';
export const EdsColorNeutral600 = '#5D6369';
export const EdsColorNeutral700 = '#383C43';
export const EdsColorNeutral800 = '#21272D';
export const EdsColorNeutralWhite = '#FFFFFF';
export const EdsColorNeutralBlack = '#161B1F';
export const EdsColorOtherMint100 = '#ECFFF5';
export const EdsColorOtherMint200 = '#B7E9CE';
export const EdsColorOtherMint300 = '#8FDCB3';
export const EdsColorOtherMint400 = '#59C88C';
export const EdsColorOtherMint500 = '#00A56A';
export const EdsColorOtherMint600 = '#008656';
export const EdsColorOtherMint700 = '#007249';
export const EdsColorOtherMint800 = '#005939';
export const EdsColorOtherYellow100 = '#FDF1D0';
export const EdsColorOtherYellow200 = '#FFEBB3';
export const EdsColorOtherYellow300 = '#FFDD80';
export const EdsColorOtherYellow400 = '#F7BE2D';
export const EdsColorOtherYellow500 = '#D18400';
export const EdsColorOtherYellow600 = '#BF7300';
export const EdsColorOtherYellow700 = '#9E5B03';
export const EdsColorOtherYellow800 = '#854C03';
export const EdsColorOtherLemon = '#F5FF8F';
export const EdsColorOtherEraser = '#F3DCE2';
export const EdsColorOtherOrange100 = '#FFF1E9';
export const EdsColorOtherOrange200 = '#FFCBA5';
export const EdsColorOtherOrange300 = '#FFAF76';
export const EdsColorOtherOrange400 = '#F6924A';
export const EdsColorOtherOrange500 = '#E06B00';
export const EdsColorOtherOrange600 = '#C64600';
export const EdsColorOtherOrange700 = '#AC3400';
export const EdsColorOtherOrange800 = '#842800';
export const EdsColorOtherRuby100 = '#FFF0F4';
export const EdsColorOtherRuby200 = '#FFCBD7';
export const EdsColorOtherRuby300 = '#FB90B0';
export const EdsColorOtherRuby400 = '#F76C96';
export const EdsColorOtherRuby500 = '#F1497B';
export const EdsColorOtherRuby600 = '#D41E52';
export const EdsColorOtherRuby700 = '#BD0044';
export const EdsColorOtherRuby800 = '#8F0134';
export const EdsColorHighlight100 = '#FF9FEC'; // @deprecated This token has been deprecated and will be removed in a future EDS release.
export const EdsColorHighlight200 = '#FFBEAA'; // @deprecated This token has been deprecated and will be removed in a future EDS release.
export const EdsColorHighlight300 = '#FCFF00'; // @deprecated This token has been deprecated and will be removed in a future EDS release.
export const EdsColorHighlight400 = '#9DFFA4'; // @deprecated This token has been deprecated and will be removed in a future EDS release.
export const EdsColorHighlight500 = '#00F1FF'; // @deprecated This token has been deprecated and will be removed in a future EDS release.
export const EdsColorHighlight600 = '#CFC9FF'; // @deprecated This token has been deprecated and will be removed in a future EDS release.
export const EdsColorInfo100 = '#F1F9FF'; // legacy token, will be removed
export const EdsColorInfo200 = '#B0D5FF'; // legacy token, will be removed
export const EdsColorInfo300 = '#7FB9FD'; // legacy token, will be removed
export const EdsColorInfo400 = '#5CA7FF'; // legacy token, will be removed
export const EdsColorInfo500 = '#328EFB'; // legacy token, will be removed
export const EdsColorInfo600 = '#1977CD'; // legacy token, will be removed
export const EdsColorInfo700 = '#0563B8'; // legacy token, will be removed
export const EdsThemeColorBackgroundNeutralDefault = '#FFFFFF';
export const EdsThemeColorBackgroundNeutralDefaultHover = '#F4F6F8';
export const EdsThemeColorBackgroundNeutralSubtle = '#F4F6F8';
export const EdsThemeColorBackgroundNeutralSubtleHover = '#E7E8EA';
export const EdsThemeColorBackgroundNeutralMedium = '#E7E8EA';
export const EdsThemeColorBackgroundNeutralMediumHover = '#C0C4C8';
export const EdsThemeColorBackgroundBrandPrimaryDefault = '#F0F0FC';
export const EdsThemeColorBackgroundBrandPrimaryStrong = '#6B65E2';
export const EdsThemeColorBackgroundBrandPrimaryStrongHover = '#3E42B1';
export const EdsThemeColorBackgroundUtilitySuccess = '#ECFFF5';
export const EdsThemeColorBackgroundUtilityWarning = '#FFF1E9';
export const EdsThemeColorBackgroundUtilityError = '#FFF0F4';
export const EdsThemeColorBackgroundGradeCompleteDefault = '#008656';
export const EdsThemeColorBackgroundGradeCompleteSubtle = '#ECFFF5';
export const EdsThemeColorBackgroundGradeReviseDefault = '#F7BE2D';
export const EdsThemeColorBackgroundGradeReviseSubtle = '#FDF1D0';
export const EdsThemeColorBackgroundGradeStopDefault = '#D41E52';
export const EdsThemeColorBackgroundGradeStopSubtle = '#FFF0F4';
export const EdsThemeColorBackgroundDisabled = '#C0C4C8';
export const EdsThemeColorBorderLinkNeutral = '#21272D'; // @deprecated This token is deprecated. Please use eds-theme-color-link-brand-text-decoration-hover, or eds-theme-color-link-neutral-text-decoration-hover instead
export const EdsThemeColorBorderLinkBrand = '#5751D2'; // @deprecated This token is deprecated. Please use eds-theme-color-link-brand-background-focus, eds-theme-color-link-brand-text-decoration, eds-theme-color-link-brand-text-decoration-hover, or eds-theme-color-link-neutral-text-decoration-hover instead
export const EdsThemeColorBorderNeutralSubtle = '#E7E8EA';
export const EdsThemeColorBorderNeutralSubtleHover = '#C0C4C8';
export const EdsThemeColorBorderNeutralDefault = '#C0C4C8';
export const EdsThemeColorBorderNeutralDefaultHover = '#999EA3';
export const EdsThemeColorBorderNeutralStrong = '#999EA3';
export const EdsThemeColorBorderNeutralStrongHover = '#878C90';
export const EdsThemeColorBorderBrandPrimarySubtle = '#E0E0F9';
export const EdsThemeColorBorderBrandPrimaryDefault =
  'var(--eds-theme-color-border-brand-primary)';
export const EdsThemeColorBorderBrandPrimary = '#C4C1F3'; // @deprecated This token is deprecated. Please use eds-theme-color-border-brand-primary-default instead
export const EdsThemeColorBorderBrandPrimaryStrong = '#A6A3EE';
export const EdsThemeColorBorderUtilitySuccessSubtle = '#B7E9CE';
export const EdsThemeColorBorderUtilitySuccessDefault = '#8FDCB3';
export const EdsThemeColorBorderUtilitySuccessStrong = '#59C88C';
export const EdsThemeColorBorderUtilityWarningSubtle = '#FFCBA5';
export const EdsThemeColorBorderUtilityWarningDefault = '#FFAF76';
export const EdsThemeColorBorderUtilityWarningStrong = '#F6924A';
export const EdsThemeColorBorderUtilityErrorSubtle = '#FFCBD7';
export const EdsThemeColorBorderUtilityErrorDefault = '#FB90B0';
export const EdsThemeColorBorderUtilityErrorStrong = '#F76C96';
export const EdsThemeColorBorderGradeComplete = '#8FDCB3';
export const EdsThemeColorBorderGradeReviseSubtle = '#FFEBB3';
export const EdsThemeColorBorderGradeReviseDefault = '#FFDD80';
export const EdsThemeColorBorderGradeReviseStrong = '#F7BE2D';
export const EdsThemeColorBorderGradeStop = '#FB90B0';
export const EdsThemeColorBorderDisabled = '#C0C4C8';
export const EdsThemeColorIconNeutralDefault = '#5D6369';
export const EdsThemeColorIconNeutralDefaultInverse = '#FFFFFF';
export const EdsThemeColorIconNeutralDefaultHover = '#383C43';
export const EdsThemeColorIconNeutralStrong = '#383C43';
export const EdsThemeColorIconNeutralStrongHover = '#21272D';
export const EdsThemeColorIconNeutralSubtle = '#878C90';
export const EdsThemeColorIconNeutralSubtleHover = '#5D6369';
export const EdsThemeColorIconLinkDefault = '#6B65E2';
export const EdsThemeColorIconLinkDefaultHover = '#5751D2';
export const EdsThemeColorIconBrandPrimary = '#8984E8';
export const EdsThemeColorIconBrandPrimaryHover = '#6B65E2';
export const EdsThemeColorIconUtilitySuccess = '#00A56A';
export const EdsThemeColorIconUtilitySuccessHover = '#008656';
export const EdsThemeColorIconUtilityWarning = '#E06B00';
export const EdsThemeColorIconUtilityWarningHover = '#C64600';
export const EdsThemeColorIconUtilityError = '#F1497B';
export const EdsThemeColorIconUtilityErrorHover = '#D41E52';
export const EdsThemeColorIconGradeComplete = '#00A56A';
export const EdsThemeColorIconGradeCompleteHover = '#00A56A';
export const EdsThemeColorIconGradeRevise = '#21272D';
export const EdsThemeColorIconGradeReviseHover = '#161B1F';
export const EdsThemeColorIconGradeStop = '#F1497B';
export const EdsThemeColorIconGradeStopHover = '#D41E52';
export const EdsThemeColorIconDisabled = '#C0C4C8';
export const EdsThemeColorTextNeutralDefault = '#383C43';
export const EdsThemeColorTextNeutralDefaultInverse = '#FFFFFF';
export const EdsThemeColorTextNeutralStrong = '#21272D';
export const EdsThemeColorTextNeutralSubtle = '#5D6369';
export const EdsThemeColorTextLinkNeutral = '#21272D'; // @deprecated This token is deprecated. Please use eds-theme-color-link-neutral-text-decoration or eds-theme-color-link-neutral-background instead.
export const EdsThemeColorTextLinkBrand = '#5751D2'; // @deprecated This token is deprecated. Please use eds-theme-color-link-brand-text-hover or eds-theme-color-link-neutral-text-hover instead.
export const EdsThemeColorTextUtilitySuccess = '#007249';
export const EdsThemeColorTextUtilityWarning = '#AC3400';
export const EdsThemeColorTextUtilityError = '#BD0044';
export const EdsThemeColorTextGradeComplete = '#007249';
export const EdsThemeColorTextGradeRevise = '#21272D';
export const EdsThemeColorTextGradeStop = '#BD0044';
export const EdsThemeColorTextDisabled = '#C0C4C8';
export const EdsThemeColorTextBrandDefault =
  'var(--eds-theme-color-text-brand-primary)';
export const EdsThemeColorTextBrandPrimary = '#5751D2'; // @deprecated This token is deprecated. Please use eds-theme-color-text-brand-default instead.
export const EdsThemeColorTransparentBlack0 = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorTransparentBlack30 = 'rgba(0, 0, 0, .3)';
export const EdsThemeColorTransparentWhite0 = 'rgba(255, 255, 255, 0)';
export const EdsThemeColorBodyBackground = '#F4F6F8';
export const EdsThemeColorBodyBackgroundInverted = '#383C43';
export const EdsThemeColorButtonPrimaryBrandBackground = '#6B65E2';
export const EdsThemeColorButtonPrimaryBrandBackgroundHover = '#5751D2';
export const EdsThemeColorButtonPrimaryBrandBackgroundActive = '#3E42B1';
export const EdsThemeColorButtonPrimaryBrandBorder = '#6B65E2';
export const EdsThemeColorButtonPrimaryBrandBorderHover = '#5751D2';
export const EdsThemeColorButtonPrimaryBrandBorderActive = '#3E42B1';
export const EdsThemeColorButtonPrimaryBrandText = '#FFFFFF';
export const EdsThemeColorButtonPrimaryBrandTextHover = '#FFFFFF';
export const EdsThemeColorButtonPrimaryBrandTextActive = '#FFFFFF';
export const EdsThemeColorButtonPrimaryErrorBackground = '#D41E52';
export const EdsThemeColorButtonPrimaryErrorBackgroundHover = '#BD0044';
export const EdsThemeColorButtonPrimaryErrorBackgroundActive = '#8F0134';
export const EdsThemeColorButtonPrimaryErrorBorder = '#D41E52';
export const EdsThemeColorButtonPrimaryErrorBorderHover = '#BD0044';
export const EdsThemeColorButtonPrimaryErrorBorderActive = '#8F0134';
export const EdsThemeColorButtonPrimaryErrorText = '#FFFFFF';
export const EdsThemeColorButtonPrimaryErrorTextHover = '#FFFFFF';
export const EdsThemeColorButtonPrimaryErrorTextActive = '#FFFFFF';
export const EdsThemeColorButtonSecondaryBrandBackground = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonSecondaryBrandBackgroundHover = '#5751D2';
export const EdsThemeColorButtonSecondaryBrandBackgroundActive = '#3E42B1';
export const EdsThemeColorButtonSecondaryBrandBorder = '#6B65E2';
export const EdsThemeColorButtonSecondaryBrandBorderHover = '#5751D2';
export const EdsThemeColorButtonSecondaryBrandBorderActive = '#3E42B1';
export const EdsThemeColorButtonSecondaryBrandText = '#5751D2';
export const EdsThemeColorButtonSecondaryBrandTextHover = '#FFFFFF';
export const EdsThemeColorButtonSecondaryBrandTextActive = '#FFFFFF';
export const EdsThemeColorButtonSecondaryBrandIcon = '#6B65E2';
export const EdsThemeColorButtonSecondaryBrandIconHover = '#FFFFFF';
export const EdsThemeColorButtonSecondaryBrandIconActive = '#FFFFFF';
export const EdsThemeColorButtonSecondaryNeutralBackground = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonSecondaryNeutralBackgroundHover = '#E7E8EA';
export const EdsThemeColorButtonSecondaryNeutralBackgroundActive = '#383C43';
export const EdsThemeColorButtonSecondaryNeutralBorder = '#5D6369';
export const EdsThemeColorButtonSecondaryNeutralBorderHover = '#5D6369';
export const EdsThemeColorButtonSecondaryNeutralBorderActive = '#383C43';
export const EdsThemeColorButtonSecondaryNeutralText = '#5D6369';
export const EdsThemeColorButtonSecondaryNeutralTextHover = '#5D6369';
export const EdsThemeColorButtonSecondaryNeutralTextActive = '#FFFFFF';
export const EdsThemeColorButtonSecondaryNeutralIcon = '#999EA3';
export const EdsThemeColorButtonSecondaryNeutralIconHover = '#999EA3';
export const EdsThemeColorButtonSecondaryNeutralIconActive = '#FFFFFF';
export const EdsThemeColorButtonSecondarySuccessBackground = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonSecondarySuccessBackgroundHover = '#007249';
export const EdsThemeColorButtonSecondarySuccessBackgroundActive = '#005939';
export const EdsThemeColorButtonSecondarySuccessBorder = '#008656';
export const EdsThemeColorButtonSecondarySuccessBorderHover = '#007249';
export const EdsThemeColorButtonSecondarySuccessBorderActive = '#005939';
export const EdsThemeColorButtonSecondarySuccessText = '#007249';
export const EdsThemeColorButtonSecondarySuccessTextHover = '#FFFFFF';
export const EdsThemeColorButtonSecondarySuccessTextActive = '#FFFFFF';
export const EdsThemeColorButtonSecondarySuccessIcon = '#008656';
export const EdsThemeColorButtonSecondarySuccessIconHover = '#FFFFFF';
export const EdsThemeColorButtonSecondarySuccessIconActive = '#FFFFFF';
export const EdsThemeColorButtonSecondaryWarningBackground = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonSecondaryWarningBackgroundHover = '#AC3400';
export const EdsThemeColorButtonSecondaryWarningBackgroundActive = '#842800';
export const EdsThemeColorButtonSecondaryWarningBorder = '#C64600';
export const EdsThemeColorButtonSecondaryWarningBorderHover = '#AC3400';
export const EdsThemeColorButtonSecondaryWarningBorderActive = '#842800';
export const EdsThemeColorButtonSecondaryWarningText = '#AC3400';
export const EdsThemeColorButtonSecondaryWarningTextHover = '#FFFFFF';
export const EdsThemeColorButtonSecondaryWarningTextActive = '#FFFFFF';
export const EdsThemeColorButtonSecondaryWarningIcon = '#C64600';
export const EdsThemeColorButtonSecondaryWarningIconHover = '#FFFFFF';
export const EdsThemeColorButtonSecondaryWarningIconActive = '#FFFFFF';
export const EdsThemeColorButtonSecondaryErrorBackground = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonSecondaryErrorBackgroundHover = '#BD0044';
export const EdsThemeColorButtonSecondaryErrorBackgroundActive = '#8F0134';
export const EdsThemeColorButtonSecondaryErrorBorder = '#D41E52';
export const EdsThemeColorButtonSecondaryErrorBorderHover = '#BD0044';
export const EdsThemeColorButtonSecondaryErrorBorderActive = '#8F0134';
export const EdsThemeColorButtonSecondaryErrorText = '#BD0044';
export const EdsThemeColorButtonSecondaryErrorTextHover = '#FFFFFF';
export const EdsThemeColorButtonSecondaryErrorTextActive = '#FFFFFF';
export const EdsThemeColorButtonSecondaryErrorIcon = '#D41E52';
export const EdsThemeColorButtonSecondaryErrorIconHover = '#FFFFFF';
export const EdsThemeColorButtonSecondaryErrorIconActive = '#FFFFFF';
export const EdsThemeColorButtonIconBrand = '#6B65E2';
export const EdsThemeColorButtonIconBrandHover = '#6B65E2';
export const EdsThemeColorButtonIconBrandActive = '#FFFFFF';
export const EdsThemeColorButtonIconBrandBackground = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonIconBrandBackgroundHover = '#E0E0F9';
export const EdsThemeColorButtonIconBrandBackgroundActive = '#5751D2';
export const EdsThemeColorButtonIconBrandBorder = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonIconBrandBorderHover = '#E0E0F9';
export const EdsThemeColorButtonIconBrandBorderActive = '#5751D2';
export const EdsThemeColorButtonIconBrandText = '#5751D2';
export const EdsThemeColorButtonIconBrandTextHover = '#5751D2';
export const EdsThemeColorButtonIconBrandTextActive = '#FFFFFF';
export const EdsThemeColorButtonIconNeutral = '#5D6369';
export const EdsThemeColorButtonIconNeutralHover = '#5D6369';
export const EdsThemeColorButtonIconNeutralActive = '#FFFFFF';
export const EdsThemeColorButtonIconNeutralBackground = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonIconNeutralBackgroundHover = '#E7E8EA';
export const EdsThemeColorButtonIconNeutralBackgroundActive = '#5D6369';
export const EdsThemeColorButtonIconNeutralBorder = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonIconNeutralBorderHover = '#E7E8EA';
export const EdsThemeColorButtonIconNeutralBorderActive = '#5D6369';
export const EdsThemeColorButtonIconNeutralText = '#5D6369';
export const EdsThemeColorButtonIconNeutralTextHover = '#5D6369';
export const EdsThemeColorButtonIconNeutralTextActive = '#FFFFFF';
export const EdsThemeColorButtonIconSuccess = '#008656';
export const EdsThemeColorButtonIconSuccessHover = '#008656';
export const EdsThemeColorButtonIconSuccessActive = '#FFFFFF';
export const EdsThemeColorButtonIconSuccessBackground = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonIconSuccessBackgroundHover = '#B7E9CE';
export const EdsThemeColorButtonIconSuccessBackgroundActive = '#007249';
export const EdsThemeColorButtonIconSuccessBorder = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonIconSuccessBorderHover = '#B7E9CE';
export const EdsThemeColorButtonIconSuccessBorderActive = '#007249';
export const EdsThemeColorButtonIconSuccessText = '#007249';
export const EdsThemeColorButtonIconSuccessTextHover = '#007249';
export const EdsThemeColorButtonIconSuccessTextActive = '#FFFFFF';
export const EdsThemeColorButtonIconWarning = '#C64600';
export const EdsThemeColorButtonIconWarningHover = '#C64600';
export const EdsThemeColorButtonIconWarningActive = '#FFFFFF';
export const EdsThemeColorButtonIconWarningBackground = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonIconWarningBackgroundHover = '#FFF1E9';
export const EdsThemeColorButtonIconWarningBackgroundActive = '#AC3400';
export const EdsThemeColorButtonIconWarningBorder = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonIconWarningBorderHover = '#FFF1E9';
export const EdsThemeColorButtonIconWarningBorderActive = '#AC3400';
export const EdsThemeColorButtonIconWarningText = '#AC3400';
export const EdsThemeColorButtonIconWarningTextHover = '#AC3400';
export const EdsThemeColorButtonIconWarningTextActive = '#FFFFFF';
export const EdsThemeColorButtonIconError = '#D41E52';
export const EdsThemeColorButtonIconErrorHover = '#D41E52';
export const EdsThemeColorButtonIconErrorActive = '#FFFFFF';
export const EdsThemeColorButtonIconErrorBackground = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonIconErrorBackgroundHover = '#FFCBD7';
export const EdsThemeColorButtonIconErrorBackgroundActive = '#BD0044';
export const EdsThemeColorButtonIconErrorBorder = 'rgba(0, 0, 0, 0)';
export const EdsThemeColorButtonIconErrorBorderHover = '#FFCBD7';
export const EdsThemeColorButtonIconErrorBorderActive = '#BD0044';
export const EdsThemeColorButtonIconErrorText = '#BD0044';
export const EdsThemeColorButtonIconErrorTextHover = '#BD0044';
export const EdsThemeColorButtonIconErrorTextActive = '#FFFFFF';
export const EdsThemeColorCheckboxBrandBackground = '#8984E8';
export const EdsThemeColorDataBarBackground = '#F4F6F8';
export const EdsThemeColorDataBarBorder = '#C0C4C8';
export const EdsThemeColorFocusRing = '#6B65E2';
export const EdsThemeColorFocusRingInverted = '#FFFFFF';
export const EdsThemeColorFormBorder = '#878C90';
export const EdsThemeColorFormBorderHover = '#21272D';
export const EdsThemeColorFormBackground = '#FFFFFF';
export const EdsThemeColorFormBackgroundHover = '#F4F6F8';
export const EdsThemeColorFormLabel = '#383C43';
export const EdsThemeColorLinkBrandText =
  'var(--eds-theme-color-text-link-neutral)';
export const EdsThemeColorLinkBrandTextHover =
  'var(--eds-theme-color-text-link-brand)';
export const EdsThemeColorLinkBrandTextFocus =
  'var(--eds-theme-color-text-neutral-default-inverse)';
export const EdsThemeColorLinkBrandTextDecoration =
  'var(--eds-theme-color-border-link-brand)';
export const EdsThemeColorLinkBrandTextDecorationHover =
  'var(--eds-theme-color-border-link-brand)';
export const EdsThemeColorLinkBrandTextDecorationFocus =
  'var(--eds-theme-color-text-neutral-default-inverse)';
export const EdsThemeColorLinkBrandBackgroundFocus =
  'var(--eds-theme-color-border-link-brand)';
export const EdsThemeColorLinkNeutralText =
  'var(--eds-theme-color-text-link-neutral)';
export const EdsThemeColorLinkNeutralTextHover =
  'var(--eds-theme-color-text-link-brand)';
export const EdsThemeColorLinkNeutralTextFocus =
  'var(--eds-theme-color-text-neutral-default-inverse)';
export const EdsThemeColorLinkNeutralTextDecoration =
  'var(--eds-theme-color-border-link-neutral)';
export const EdsThemeColorLinkNeutralTextDecorationHover =
  'var(--eds-theme-color-border-link-brand)';
export const EdsThemeColorLinkNeutralTextDecorationFocus =
  'var(--eds-theme-color-text-neutral-default-inverse)';
export const EdsThemeColorLinkNeutralBackgroundFocus =
  'var(--eds-theme-color-border-link-neutral)';
export const EdsThemeColorModalBrandHeaderBackground = '#8984E8';
export const EdsThemeColorProgressBarBackground = '#E7E8EA';
export const EdsThemeColorProgressBarBorder = '#E7E8EA';
export const EdsThemeColorRadioBrandBackground = '#8984E8';
export const EdsThemeColorTextHighlightForeground = '#21272D';
export const EdsThemeColorTextHighlightBackground = '#F5FF8F';
export const LegacyColorGray50 = '#F8F9FC';
export const LegacyColorGray100 = '#EBEBEC';
export const LegacyColorGray200 = '#D8D8D9';
export const LegacyColorGray300 = '#C5C5C6';
export const LegacyColorGray500 = '#9F9FA0';
export const LegacyColorGray700 = '#78797A';
export const LegacyColorGray1000 = '#3F4041';
export const LegacyColorBlack = '#2C2D2E';
export const LegacyColorRed100 = '#F7DDDD';
export const LegacyColorRed200 = '#F25252';
export const LegacyColorGreen100 = '#E1F0E7';
export const LegacyColorGreen200 = '#6CC188';
export const LegacyColorGreen300 = '#457B57';
export const LegacyColorYellow200 = '#FFC55B';
export const LegacyColorYellow300 = '#A46900';
export const LegacyColorYellow400 = '#644C1F';
export const LegacyColorPurple200 = '#7686D3';
export const LegacyColorPurple300 = '#5761BA';
export const LegacyColorPurple400 = '#32417C';
